### ISSUE TITLE
thoughts about truth maintenance?

### ISSUE THREAD

**Issue by tve** [anywhichway/rule-reactor#14]
One of the hurdles I've been encountering is writing inference rules that produce derived facts that get retracted when the facts that support the inference no longer exist. I.e. truth maintenance. Drools has an `insertLogical` operator that supports this type of rules. Any thoughts for how to do this with rule-reactor?

It is usually possible to write a rule and its complement such that a fact gets asserted and retracted by this pair as the condition's facts are modified, but where that fails is when one of the condition's facts gets retracted because no rule triggers at that point.

**Comment by anywhichway** [comment]
I am very familiar  with truth maintenance. It is not likely we will add it to rule-reactor due to the tracking overhead required. We did build a prototype internally that supported both truth maintenance and fuzzy logic.

Is there a reason you are trying to steer clear of Drools? It has much deeper and broader support, although the syntax and debugging are awkward. I prefer Clips myself.

It is not likely rule-reactor will ever be at the level of functionality of Drools. It is intended as a light weight approach.

**Comment by tve** [comment]
Drools is such a monster, plus the language is really awkward. I need something that is lightwight and can process lots of JSON objects... I was looking at drools more to understand what I'm missing...

I'll have to think about how much overhead the truth maintenance really requires, I must be missing something...

**Comment by anywhichway** [comment]
Well we are on the same page there! This is exactly why we created rule-reactor. 

Truth maintenance requires two things:

1) More extensive parsing of LHS
2) Back-end tracking of what rule changed what fact under what bindings. Because we do not maintain a pattern and join net of bindings now, the relative overhead gets high.

**Comment by tve** [comment]
The system I have is real-time/dynamic in the sense that facts are updated in close to real time (speaking on the order of minutes) and the rules are rerun after each fact update. I'm finding it very difficult to do anything of substance involving inference without having to write lots of extra rules using not-exist quantification. Maybe I'm missing some tricks...

Example:
- Domains: Cars, Colors
- The Cars facts are updated every minute based on what's in the lot, each car has a color attribute.
- Infer the number of cars of each color and assert an inferred fact of the form {color:"red", count:10} that records how many cars of each color are available.
- Note: the colors are not a finite known set, new colors appear all the time (marketing...).

I believe the following would be sufficient if there was a notion of logical assertion:
```
// create a new color when we see a car with it
createRule("enumerate-colors", 0, {car: Car},
  function(car) { return not(exists({color: Color}, function(color) { return car.color = color.name; })) },
  function(car) { assert(new Color({name: car.color})); });

// for each color, update the number of cars with it
createRule("count-colors", 0, {color: Color},
  function(color) { return exists({car: Car}, function(car) { return car.color == color.name; }); },
  function(color, cars) { color.count = cars.length; }); // assumes RHS binding of exists result
```

where this fails in rule-reactor is when the last car of a color goes away, so I also need something like:
```
// need to delete colors that no longer exist
createRule("unused-color", -1, {color: Color},
  function(color) { return not(exists({car: Car}, function(color) { return car.color = color.name; }));
  },
  function(color) { reactor.retract(color); }
);
```

Now suppose I have a set of "Alert" facts that enumerate various alerts that someone should receive, one being when only one car of a certain color is left. The rule that creates the alert fact is simple, but another rule using not-exists is needed to retract it when, for example, new cars show up with that color. And this need for these extra rules keeps cascading.

Am I doing things wrong? Do you not use rule-reactor for this type of use-case?

**Comment by anywhichway** [comment]
You are not doing anything wrong. This is are classic issues with rule based systems, i.e. counting things and truth maintenance. This being said, rule-reactor was designed so that you can also use native Javascript programming when necessary. Every class referenced in a domain rule has an instances property added to its constructor, e.g. Cars.instances. The value is an array. You can simply use filter to get an array of cars with a given color, e.g. 

```
(color) => { Cars.instances.filter((car) => { return car.color===color.name; }); }
```

So, you can re-write the rule as this:

```
createRule("count-colors", 0, {color: Color},
  function(color) { return exists({car: Car}, function(car) { return car.color == color.name; }); },
  function(color) { color.count = ((color) => { Car.instances.filter((car) => { return car.color===color; }); }; }))().length; } 
```

This covers simple exists quantification counts. More complex exists conditions make the RHS computation substantially more difficult.

**Comment by tve** [comment]
I had not spotted the instances property, thanks for pointing this out!
